# Generated by Django 4.2.10 on 2024-03-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_department_person_user_type_student_person_account_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='account',
            new_name='person',
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=1),
        ),
    ]
