# Generated by Django 4.2.10 on 2024-03-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_account_student_person_alter_student_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePhoto', models.ImageField(upload_to='profile_photos/Clubs')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField(max_length=5000)),
            ],
        ),
    ]
