# Generated by Django 4.2.10 on 2024-03-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
